version: '3.9'

services:
  signtoalldb:
    container_name: signtoalldb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456789
      - MONGO_INITDB_DATABASE=signtoalldb
    volumes:
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - mongodata:/data/db

  # myapp:
  #   container_name: signtoall-back
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   networks:
  #     - nesjs-network
  #   volumes:
  #     - ../:/usr/src/app
  #     - ../node_modules:/usr/src/app/node_modules
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   restart: unless-stopped
  #   depends_on:
  #     - signtoalldb
